export default [
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/0/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/1/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/2/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/3/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/4/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/5/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/6/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/7/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "apiVersion" },
    message: "must have required property 'apiVersion'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "kind" },
    message: "must have required property 'kind'",
  },
  {
    instancePath: "",
    schemaPath: "#/required",
    keyword: "required",
    params: { missingProperty: "metadata" },
    message: "must have required property 'metadata'",
  },
  {
    instancePath: "",
    schemaPath: "#/additionalProperties",
    keyword: "additionalProperties",
    params: { additionalProperty: "teset" },
    message: "must NOT have additional properties",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf/8/allOf/1/required",
    keyword: "required",
    params: { missingProperty: "spec" },
    message: "must have required property 'spec'",
  },
  {
    instancePath: "",
    schemaPath: "#/anyOf",
    keyword: "anyOf",
    params: {},
    message: "must match a schema in anyOf",
  },
  {
    instancePath: "/apiVersion",
    schemaPath: "#/allOf/1/properties/apiVersion/enum",
    keyword: "enum",
    params: { allowedValues: ["apiversion"] },
    message: "must be equal to one of the allowed values",
  },
] as const;
